# Generated by Django 5.0.9 on 2025-09-02 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("processor", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="exemptrule",
            name="rule_id",
        ),
    ]
