# Generated by Django 5.0.9 on 2025-08-19 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="IWO_Details_PDF",
            fields=[
                ("IWO_ID", models.AutoField(primary_key=True, serialize=False)),
                ("cid", models.CharField(max_length=250)),
                ("ee_id", models.CharField(max_length=250)),
                ("IWO_Status", models.CharField(max_length=250)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "iwo_details_pdf",
            },
        ),
        migrations.CreateModel(
            name="IWOPDFFiles",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("pdf_url", models.URLField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "iwo_pdf_files",
            },
        ),
        migrations.CreateModel(
            name="setting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("employer_id", models.IntegerField()),
                ("modes", models.BooleanField()),
                ("visibilitys", models.BooleanField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "setting",
            },
        ),
        migrations.CreateModel(
            name="employee_batch_data",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ee_id", models.CharField(max_length=255, unique=True)),
                ("case_id", models.CharField(max_length=255, unique=True)),
                ("work_state", models.CharField(max_length=255)),
                (
                    "no_of_exemption_including_self",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("pay_period", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "filing_status",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "age",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("is_blind", models.BooleanField(blank=True, null=True)),
                ("is_spouse_blind", models.BooleanField(blank=True, null=True)),
                (
                    "spouse_age",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "support_second_family",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "no_of_student_default_loan",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "arrears_greater_than_12_weeks",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "no_of_dependent_exemption",
                    models.IntegerField(blank=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "employee_batch_data",
                "indexes": [
                    models.Index(
                        fields=["case_id"], name="employee_ba_case_id_37c297_idx"
                    ),
                    models.Index(
                        fields=["ee_id", "case_id"], name="employee_ba_ee_id_723db9_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="employee_detail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ee_id", models.CharField(max_length=255)),
                ("case_id", models.CharField(max_length=255)),
                ("age", models.CharField(max_length=255)),
                ("social_security_number", models.CharField(max_length=255)),
                ("is_blind", models.BooleanField(blank=True, null=True)),
                ("home_state", models.CharField(max_length=255)),
                ("work_state", models.CharField(max_length=255)),
                ("gender", models.CharField(blank=True, max_length=255, null=True)),
                ("number_of_exemptions", models.IntegerField()),
                ("filing_status", models.CharField(max_length=255)),
                ("marital_status", models.CharField(max_length=255)),
                ("number_of_student_default_loan", models.IntegerField()),
                ("support_second_family", models.BooleanField()),
                ("spouse_age", models.IntegerField(blank=True, null=True)),
                ("is_spouse_blind", models.BooleanField(blank=True, null=True)),
                ("record_import", models.DateTimeField(auto_now_add=True)),
                ("record_updated", models.DateTimeField(auto_now_add=True)),
                ("garnishment_fees_status", models.BooleanField()),
                ("garnishment_fees_suspended_till", models.DateField()),
                ("pay_period", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "employee_detail",
                "indexes": [
                    models.Index(fields=["ee_id"], name="employee_de_ee_id_3472c7_idx"),
                    models.Index(
                        fields=["case_id"], name="employee_de_case_id_553388_idx"
                    ),
                    models.Index(
                        fields=["ee_id", "case_id"], name="employee_de_ee_id_c03ba3_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="garnishment_batch_data",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ee_id", models.CharField(max_length=255)),
                ("case_id", models.CharField(max_length=255, unique=True)),
                ("garnishment_type", models.CharField(max_length=255)),
                (
                    "ordered_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "arrear_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "current_medical_support",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "past_due_medical_support",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "current_spousal_support",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "past_due_spousal_support",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "garnishment_batch_data",
                "indexes": [
                    models.Index(fields=["ee_id"], name="garnishment_ee_id_52a382_idx"),
                    models.Index(
                        fields=["ee_id", "case_id"], name="garnishment_ee_id_7e12c7_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="garnishment_order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("eeid", models.CharField(max_length=254)),
                ("fein", models.CharField(max_length=254)),
                ("case_id", models.CharField(blank=True, max_length=255, null=True)),
                ("work_state", models.CharField(max_length=255)),
                ("type", models.CharField(max_length=255)),
                ("sdu", models.CharField(blank=True, max_length=255, null=True)),
                ("start_date", models.DateField(blank=True, max_length=255, null=True)),
                ("end_date", models.DateField(blank=True, max_length=255, null=True)),
                (
                    "amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("arrear_greater_than_12_weeks", models.BooleanField(default=False)),
                (
                    "arrear_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("record_updated", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "garnishment_order",
                "indexes": [
                    models.Index(fields=["eeid"], name="garnishment_eeid_214ee0_idx"),
                    models.Index(
                        fields=["case_id"], name="garnishment_case_id_1310e1_idx"
                    ),
                    models.Index(
                        fields=["case_id", "eeid"],
                        name="garnishment_case_id_f766b9_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="payroll",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cid", models.CharField(max_length=255)),
                ("eeid", models.CharField(max_length=255)),
                ("payroll_date", models.DateField()),
                ("pay_date", models.DateField()),
                (
                    "gross_pay",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "net_pay",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "tax_federal_income_tax",
                    models.DecimalField(decimal_places=2, max_digits=13),
                ),
                (
                    "tax_state_tax",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "tax_local_tax",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "tax_medicare_tax",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("tax_social_security", models.CharField(max_length=255)),
                (
                    "deduction_sdi",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "deduction_medical_insurance",
                    models.DecimalField(decimal_places=2, max_digits=13),
                ),
                (
                    "deduction_401k",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "deduction_union_dues",
                    models.DecimalField(decimal_places=2, max_digits=13),
                ),
                (
                    "deduction_voluntary",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("type", models.CharField(max_length=255)),
                (
                    "amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "payroll",
                "indexes": [
                    models.Index(fields=["cid"], name="payroll_cid_00d36f_idx"),
                    models.Index(fields=["eeid"], name="payroll_eeid_6282ba_idx"),
                    models.Index(fields=["cid", "eeid"], name="payroll_cid_4800d3_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="payroll_taxes_batch_data",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ee_id", models.CharField(max_length=255, unique=True)),
                ("case_id", models.CharField(max_length=255, unique=True)),
                ("wages", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "commission_and_bonus",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "non_accountable_allowances",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "gross_pay",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "debt",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "exemption_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "net_pay",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "federal_income_tax",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "social_security_tax",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "medicare_tax",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "state_tax",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "local_tax",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "union_dues",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "wilmington_tax",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "medical_insurance_pretax",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "industrial_insurance",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "life_insurance",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "california_sdi",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "payroll_taxes_batch_data",
                "indexes": [
                    models.Index(
                        fields=["case_id"], name="payroll_tax_case_id_64fd14_idx"
                    ),
                    models.Index(
                        fields=["ee_id", "case_id"], name="payroll_tax_ee_id_ae82ff_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="withholding_order_data",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.CharField(max_length=250)),
                ("state", models.CharField(max_length=255)),
                ("city", models.CharField(max_length=255)),
                ("case_id", models.CharField(max_length=255)),
                ("order_id", models.CharField(max_length=255)),
                ("remittance_id", models.CharField(max_length=255)),
                ("fein", models.CharField(max_length=255)),
                ("employee_name", models.CharField(max_length=255)),
                (
                    "child1_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "child2_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "child3_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "child4_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "child5_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "child6_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("child1_dob", models.CharField(blank=True, max_length=255, null=True)),
                ("child2_dob", models.CharField(blank=True, max_length=255, null=True)),
                ("child3_dob", models.CharField(blank=True, max_length=255, null=True)),
                ("child4_dob", models.CharField(blank=True, max_length=255, null=True)),
                ("child5_dob", models.CharField(blank=True, max_length=255, null=True)),
                ("child6_dob", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "past_due_cash_medical_support_payperiod",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "current_spousal_support_payperiod",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "past_due_spousal_support_payperiod",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "other_order_payperiod",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "total_amount_to_withhold_payperiod",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "current_child_support_payperiod",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "past_due_child_support_payperiod",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "current_cash_medical_support_payperiod",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "current_child_support_amt",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "past_due_cash_medical_support",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "total_amt_to_withhold",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "lump_sum_payment_amt",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "disposable_income_percentage",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "current_spousal_support",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "other_order_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "ordered_amount_per_weekly",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "ordered_amount_per_biweekly",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "ordered_amount_per_monthly",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "ordered_amount_per_semimonthly",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "final_payment_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "past_due_child_support",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "past_due_spousal_support",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "current_cash_medical_support",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "termination_date",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "tribal_payee",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "income_withholding_order",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "arrears_greater_than_12_weeks",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "one_time_order",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "termination_of_iwo",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "amended_iwo",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "never_employed_no_income",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "not_currently_employed",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "child_support_agency",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("court", models.CharField(blank=True, max_length=255, null=True)),
                ("attorney", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "private_individual",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "withholding_order_data",
                "indexes": [
                    models.Index(fields=["id"], name="withholding_id_7e4518_idx")
                ],
            },
        ),
    ]
