# Generated by Django 5.0.9 on 2025-08-19 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="disposable_earning_rules",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("state", models.CharField(max_length=255)),
                ("disposable_earnings", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "disposable_earning_rules",
            },
        ),
        migrations.CreateModel(
            name="FedFilingStatus",
            fields=[
                ("fs_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "default_exempt_amt",
                    models.FloatField(
                        help_text="Default exempt amount for older/blind"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "fed_filing_status",
            },
        ),
        migrations.CreateModel(
            name="GarnishmentType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "garnishment_type",
            },
        ),
        migrations.CreateModel(
            name="IRSPublication1494",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "irs_publication_1494",
            },
        ),
        migrations.CreateModel(
            name="PayPeriod",
            fields=[
                ("pp_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "payperiod",
            },
        ),
        migrations.CreateModel(
            name="State",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("state_code", models.CharField(max_length=100, unique=True)),
                ("state", models.CharField(blank=True, max_length=100, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "state_data",
            },
        ),
        migrations.CreateModel(
            name="creditor_debt_applied_rule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ee_id", models.CharField(blank=True, max_length=255, null=True)),
                ("case_id", models.CharField(blank=True, max_length=255, null=True)),
                ("state", models.CharField(blank=True, max_length=255, null=True)),
                ("pay_period", models.CharField(max_length=255)),
                (
                    "withholding_cap",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "withholding_basis",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "creditor_debt_applied_rule",
                "indexes": [
                    models.Index(fields=["state"], name="creditor_de_state_311d07_idx"),
                    models.Index(
                        fields=["pay_period", "state"],
                        name="creditor_de_pay_per_58e013_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="creditor_debt_exempt_amt_config",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("state", models.CharField(max_length=50)),
                ("pay_period", models.CharField(max_length=50)),
                (
                    "minimum_hourly_wage_basis",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "minimum_wage_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "multiplier_lt",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "condition_expression_lt",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "lower_threshold_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "lower_threshold_percent1",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "lower_threshold_percent2",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "multiplier_mid",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "condition_expression_mid",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "mid_threshold_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "mid_threshold_percent",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "multiplier_ut",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "condition_expression_ut",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "upper_threshold_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "upper_threshold_percent",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "de_range_lower_to_upper_threshold_percent",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "de_range_lower_to_mid_threshold_percent",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "de_range_mid_to_upper_threshold_percent",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "deducted_basis_percent",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "is_filing_status",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "filing_status_percent",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "exempt_amt",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "creditor_debt_exempt_amt_config",
                "indexes": [
                    models.Index(fields=["state"], name="creditor_de_state_ffad43_idx"),
                    models.Index(
                        fields=["pay_period", "state"],
                        name="creditor_de_pay_per_7d1d61_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="creditor_debt_rule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("state", models.CharField(max_length=255, unique=True)),
                ("rule", models.CharField(blank=True, max_length=2500, null=True)),
                (
                    "deduction_basis",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "withholding_limit",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "creditor_debt_rule",
                "indexes": [
                    models.Index(fields=["state"], name="creditor_de_state_5c0922_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="creditor_debt_rule_edit_permission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("state", models.CharField(max_length=255)),
                (
                    "description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "deduction_basis",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "withholding_limit",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "creditor_debt_rule_edit_permission",
                "indexes": [
                    models.Index(fields=["state"], name="creditor_de_state_8e10a1_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="garnishment_fees",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("state", models.CharField(max_length=255)),
                ("type", models.CharField(max_length=255)),
                ("pay_period", models.CharField(max_length=255)),
                ("amount", models.CharField(blank=True, max_length=255, null=True)),
                ("status", models.CharField(max_length=255)),
                ("rules", models.CharField(max_length=255)),
                ("payable_by", models.CharField(blank=True, max_length=255, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "garnishment_fees",
                "indexes": [
                    models.Index(fields=["state"], name="garnishment_state_edd343_idx"),
                    models.Index(fields=["type"], name="garnishment_type_699297_idx"),
                    models.Index(
                        fields=["pay_period", "state"],
                        name="garnishment_pay_per_69cafa_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="garnishment_fees_rules",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rule", models.CharField(max_length=255)),
                ("maximum_fee_deduction", models.CharField(max_length=255)),
                (
                    "per_pay_period",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("per_month", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "per_remittance",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "garnishment_fees_rules",
                "indexes": [
                    models.Index(fields=["rule"], name="garnishment_rule_a3f9c2_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="garnishment_fees_states_rule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("state", models.CharField(max_length=255)),
                ("pay_period", models.CharField(max_length=255)),
                ("rule", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "garnishment_fees_states_rule",
                "indexes": [
                    models.Index(fields=["state"], name="garnishment_state_e90087_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="PriorityOrders",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("priority_order", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "garnishment_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="garnish_processing_app.garnishmenttype",
                    ),
                ),
                (
                    "state",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="garnish_processing_app.state",
                    ),
                ),
            ],
            options={
                "db_table": "priority_order",
            },
        ),
        migrations.CreateModel(
            name="ExemptConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("debt_type", models.CharField(blank=True, max_length=100, null=True)),
                ("is_filing_status", models.BooleanField(default=False)),
                ("wage_basis", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "wage_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("percent_limit", models.IntegerField(blank=True, null=True)),
                ("start_gt_5dec24", models.BooleanField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "pay_period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="garnish_processing_app.payperiod",
                    ),
                ),
                (
                    "state",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="garnish_processing_app.state",
                    ),
                ),
            ],
            options={
                "db_table": "exempt_config",
            },
        ),
        migrations.CreateModel(
            name="state_tax_levy_applied_rule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ee_id", models.CharField(blank=True, max_length=1000, null=True)),
                ("case_id", models.CharField(blank=True, max_length=1000, null=True)),
                ("state", models.CharField(blank=True, max_length=1000, null=True)),
                ("pay_period", models.CharField(max_length=1000)),
                (
                    "deduction_basis",
                    models.CharField(blank=True, max_length=1000, null=True),
                ),
                (
                    "withholding_cap",
                    models.CharField(blank=True, max_length=1000, null=True),
                ),
                (
                    "withholding_limit",
                    models.CharField(blank=True, max_length=1000, null=True),
                ),
                (
                    "withholding_basis",
                    models.CharField(blank=True, max_length=1000, null=True),
                ),
                (
                    "withholding_limit_rule",
                    models.CharField(blank=True, max_length=1000, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "state_tax_levy_applied_rule",
                "indexes": [
                    models.Index(
                        fields=["case_id"], name="state_tax_l_case_id_cc0c54_idx"
                    ),
                    models.Index(fields=["ee_id"], name="state_tax_l_ee_id_65c524_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="state_tax_levy_config",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("state", models.CharField(max_length=255, unique=True)),
                (
                    "deduction_basis",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "withholding_limit",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "withholding_limit_rule",
                    models.CharField(blank=True, max_length=455, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "state_tax_levy_config",
                "indexes": [
                    models.Index(fields=["state"], name="state_tax_l_state_429916_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="state_tax_levy_exempt_amt_config",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("state", models.CharField(max_length=255)),
                ("pay_period", models.CharField(max_length=255)),
                ("minimum_hourly_wage_basis", models.CharField(max_length=255)),
                (
                    "minimum_wage_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "multiplier_lt",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "condition_expression_lt",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "lower_threshold_amount",
                    models.DecimalField(decimal_places=4, max_digits=10),
                ),
                (
                    "multiplier_ut",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "condition_expression_ut",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "upper_threshold_amount",
                    models.DecimalField(decimal_places=4, max_digits=10),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "state_tax_levy_exempt_amt_config",
                "indexes": [
                    models.Index(fields=["state"], name="state_tax_l_state_1e05e1_idx"),
                    models.Index(
                        fields=["pay_period", "state"],
                        name="state_tax_l_pay_per_771686_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="state_tax_levy_rule_edit_permission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("state", models.CharField(max_length=255)),
                (
                    "description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "deduction_basis",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "withholding_limit",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "state_tax_levy_rule_edit_permission",
                "indexes": [
                    models.Index(fields=["state"], name="state_tax_l_state_0c25e6_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="ThresholdAmount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "lower_threshold_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "lower_threshold_percent1",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "lower_threshold_percent2",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "mid_threshold_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "mid_threshold_percent",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "upper_threshold_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "upper_threshold_percent",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "de_range_lower_to_upper_threshold_percent",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "de_range_lower_to_mid_threshold_percent",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "de_range_mid_to_upper_threshold_percent",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "exempt_amt",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "filing_status_percent",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "config",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="garnish_processing_app.exemptconfig",
                    ),
                ),
            ],
            options={
                "db_table": "threshold_amount",
            },
        ),
        migrations.CreateModel(
            name="ThresholdCondition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "multiplier_lt",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "condition_expression_lt",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "multiplier_mid",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "condition_expression_mid",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "multiplier_ut",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "condition_expression_ut",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "threshold",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="garnish_processing_app.thresholdamount",
                    ),
                ),
            ],
            options={
                "db_table": "threshold_condition",
            },
        ),
        migrations.CreateModel(
            name="WithholdingRules",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rule", models.CharField(max_length=255)),
                ("allocation_method", models.CharField(max_length=255)),
                ("withholding_limit", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "state",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="garnish_processing_app.state",
                    ),
                ),
            ],
            options={
                "db_table": "withholding_rules",
            },
        ),
        migrations.CreateModel(
            name="WithholdingLimit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("wl", models.CharField(max_length=10)),
                (
                    "supports_2nd_family",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "arrears_of_more_than_12_weeks",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "number_of_orders",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "weekly_de_code",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "rule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="limits",
                        to="garnish_processing_app.withholdingrules",
                    ),
                ),
            ],
            options={
                "db_table": "withholding_limit",
            },
        ),
        migrations.CreateModel(
            name="AddExemptions",
            fields=[
                ("add_id", models.AutoField(primary_key=True, serialize=False)),
                ("num_exemptions", models.PositiveIntegerField()),
                (
                    "daily",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "weekly",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "biweekly",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "semimonthly",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "monthly",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "fs",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="garnish_processing_app.fedfilingstatus",
                    ),
                ),
                (
                    "year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="garnish_processing_app.irspublication1494",
                    ),
                ),
            ],
            options={
                "db_table": "add_exemptions",
                "unique_together": {("year", "fs", "num_exemptions")},
            },
        ),
        migrations.CreateModel(
            name="StdExemptions",
            fields=[
                ("std_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "num_exemptions",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("exempt_amt", models.CharField(blank=True, max_length=100, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "fs",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="garnish_processing_app.fedfilingstatus",
                    ),
                ),
                (
                    "pp",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="garnish_processing_app.payperiod",
                    ),
                ),
                (
                    "year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="garnish_processing_app.irspublication1494",
                    ),
                ),
            ],
            options={
                "db_table": "std_exemptions",
                "unique_together": {("year", "fs", "pp", "num_exemptions")},
            },
        ),
    ]
