# Generated by Django 4.2.20 on 2025-05-20 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Firms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.CharField(max_length=100, unique=True)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('login_status', models.BooleanField(default=False)),
                ('firm_logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('firm_name', models.CharField(max_length=255)),
                ('firm_weburl', models.URLField(blank=True, null=True)),
                ('official_emailid', models.EmailField(max_length=254)),
                ('email_otp', models.CharField(blank=True, max_length=6, null=True)),
                ('email_otp_status', models.BooleanField(default=False)),
                ('contact_number', models.CharField(max_length=15)),
                ('mobile_otp', models.CharField(blank=True, max_length=6, null=True)),
                ('mobile_otp_status', models.BooleanField(default=False)),
                ('address', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='master_app.city')),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='master_app.country')),
                ('state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='master_app.state')),
            ],
            options={
                'db_table': 'firm',
            },
        ),
        migrations.CreateModel(
            name='BusinessOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(max_length=255)),
                ('contact_number', models.CharField(max_length=15)),
                ('email_id', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account_id', models.OneToOneField(db_column='account_id', on_delete=django.db.models.deletion.CASCADE, to='company_app.firms', to_field='account_id')),
            ],
            options={
                'db_table': 'business_owner',
            },
        ),
        migrations.CreateModel(
            name='BusinessInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firm_type', models.CharField(max_length=100)),
                ('firm_registration_type', models.CharField(max_length=100, verbose_name='Firm Registration Type')),
                ('about_firm', models.TextField(blank=True, null=True)),
                ('registration_certificate', models.FileField(blank=True, null=True, upload_to='certificates/')),
                ('pan_number', models.CharField(blank=True, max_length=10, null=True)),
                ('pan_front', models.FileField(blank=True, null=True, upload_to='pan_docs/')),
                ('pan_back', models.FileField(blank=True, null=True, upload_to='pan_docs/')),
                ('aadhaar_number', models.CharField(blank=True, max_length=12, null=True)),
                ('aadhaar_front', models.FileField(blank=True, null=True, upload_to='aadhaar_docs/')),
                ('aadhaar_back', models.FileField(blank=True, null=True, upload_to='aadhaar_docs/')),
                ('tax_type', models.CharField(choices=[('GST', 'GST'), ('Non GST', 'Non GST')], max_length=50)),
                ('gst_number', models.CharField(blank=True, max_length=20, null=True)),
                ('gst_certificate', models.FileField(blank=True, null=True, upload_to='gst_docs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account_id', models.OneToOneField(db_column='account_id', on_delete=django.db.models.deletion.CASCADE, to='company_app.firms', to_field='account_id')),
            ],
            options={
                'db_table': 'business_information',
            },
        ),
    ]
