# Generated by Django 4.2.20 on 2025-05-20 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessTaxDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gst_number', models.CharField(blank=True, max_length=15, null=True)),
                ('gst_certificate', models.FileField(blank=True, null=True, upload_to='documents/gst/')),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company_app.firms')),
            ],
            options={
                'verbose_name': 'Business Tax Detail',
                'verbose_name_plural': 'Business Tax Details',
                'db_table': 'business_taxdetail',
            },
        ),
        migrations.CreateModel(
            name='BusinessDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('PAN', 'PAN'), ('AADHAAR', 'AADHAAR')], max_length=255)),
                ('pan_number', models.CharField(blank=True, max_length=10, null=True)),
                ('aadhaar_number', models.CharField(blank=True, max_length=12, null=True)),
                ('pan_front', models.ImageField(blank=True, null=True, upload_to='documents/pan/')),
                ('pan_back', models.ImageField(blank=True, null=True, upload_to='documents/pan/')),
                ('aadhaar_front', models.ImageField(blank=True, null=True, upload_to='documents/aadhaar/')),
                ('aadhaar_back', models.ImageField(blank=True, null=True, upload_to='documents/aadhaar/')),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company_app.firms')),
            ],
            options={
                'verbose_name': 'Business Document',
                'verbose_name_plural': 'Business Documents',
                'db_table': 'business_document',
            },
        ),
    ]
