# Generated by Django 4.2.20 on 2025-05-21 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company_app', '0005_firms_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessinformation',
            name='account_id',
            field=models.OneToOneField(db_column='account_id', on_delete=django.db.models.deletion.CASCADE, related_name='business_info', to='company_app.firms', to_field='account_id'),
        ),
        migrations.AlterField(
            model_name='businessowner',
            name='account_id',
            field=models.OneToOneField(db_column='account_id', on_delete=django.db.models.deletion.CASCADE, related_name='business_owner_info', to='company_app.firms', to_field='account_id'),
        ),
    ]
