# Generated by Django 4.2.20 on 2025-05-20 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_app', '0002_businesstaxdetail_businessdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='firms',
            name='temp_password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
