# Generated by Django 4.2.20 on 2025-05-20 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company_app', '0003_firms_temp_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businesstaxdetail',
            name='firm',
        ),
        migrations.DeleteModel(
            name='BusinessDocument',
        ),
        migrations.DeleteModel(
            name='BusinessTaxDetail',
        ),
    ]
