# Generated by Django 4.2.20 on 2025-05-20 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_app', '0004_remove_businesstaxdetail_firm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='firms',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
