# Generated by Django 5.0.9 on 2025-09-16 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeedetail',
            name='record_import',
        ),
        migrations.RemoveField(
            model_name='employeedetail',
            name='record_updated',
        ),
        migrations.AddField(
            model_name='client',
            name='service_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='employeedetail',
            name='first_name',
            field=models.CharField(default='John', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employeedetail',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='employeedetail',
            name='middle_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
