# Generated by Django 4.2.15 on 2025-10-03 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_remove_employeedetail_record_import_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='garnishmentorder',
            name='arrear_greater_than_12_weeks',
        ),
    ]
