# Generated by Django 4.2.15 on 2025-10-07 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0003_remove_garnishmentorder_arrear_gt_12_weeks'),
    ]

    operations = [
        migrations.AddField(
            model_name='garnishmentorder',
            name='arrear_greater_than_12_weeks',
            field=models.BooleanField(default=False),
        ),
    ]
